export const MUTUAL_FUND_AMCS: Record<string, string[]> = {
    '786 Investments Limited': [
        '786 Islamic Money Market Fund',
        '786 Smart Fund'
    ],
    'ABL Asset Management Company Limited': [
        'ABL Cash Fund',
        'ABL Financial Planning Fund',
        'ABL Financial Sector Fund',
        'ABL Fixed Rate Plans',
        'ABL Government Securities Fund',
        'ABL Income Fund',
        'ABL Islamic Asset Allocation Fund',
        'ABL Islamic Cash Fund',
        'ABL Islamic Dedicated Stock Fund',
        'ABL Islamic Financial Planning Fund',
        'ABL Islamic Income Fund',
        'ABL Islamic Money Market Plan',
        'ABL Islamic Pension Fund',
        'ABL Islamic Sovereign Plan',
        'ABL Islamic Stock Fund',
        'ABL Money Market Plan',
        'ABL Optimal Asset Allocation Fund',
        'ABL Pension Fund',
        'ABL Special Saving Fund',
        'ABL Stock Fund',
        'ABL GOKP Pension Funds',
        'ABL GOPB Pension Funds'
    ],
    'AKD Investment Management Limited': [
        'AKD Aggressive Income Fund',
        'AKD Cash Fund',
        'AKD Index Tracker Fund',
        'AKD Islamic Cash Fund',
        'AKD Islamic Income Fund',
        'AKD Islamic Stock Fund',
        'AKD Opportunity Fund'
    ],
    'AL Habib Asset Management Limited': [
        'AL Habib Asset Allocation Fund',
        'AL Habib Cash Fund',
        'AL Habib Fixed Return Fund (multiple plans)',
        'AL Habib Government Securities Fund',
        'AL Habib Income Fund',
        'AL Habib Islamic Cash Fund',
        'AL Habib Islamic Income Fund',
        'AL Habib Islamic Munafa Fund',
        'AL Habib Islamic Pension Fund',
        'AL Habib Islamic Savings Fund',
        'AL Habib Islamic Stock Fund',
        'AL Habib Money Market Fund',
        'AL Habib Pension Fund',
        'AL Habib Sovereign Income Fund',
        'AL Habib Stock Fund',
        'AL Habib GOKP Pension Funds'
    ],
    'Al Meezan Investment Management Limited': [
        'Al Meezan Mutual Fund',
        'Meezan Asset Allocation Fund',
        'Meezan Balanced Fund',
        'Meezan Cash Fund',
        'Meezan Daily Income Fund',
        'Meezan Dedicated Equity Fund',
        'Meezan Dynamic Asset Allocation Fund',
        'Meezan Energy Fund',
        'Meezan Financial Planning Fund of Funds',
        'Meezan Gold Fund',
        'Meezan Islamic Asaan Cash Fund',
        'Meezan Islamic Fund',
        'Meezan Islamic Income Fund',
        'Meezan Paidaar Munafa Plans',
        'Meezan Pakistan ETF',
        'Meezan Rozana Amdani Fund',
        'Meezan Sovereign Fund',
        'Meezan Strategic Allocation Fund',
        'Meezan Tahaffuz Pension Fund',
        'Meezan GOKP / Punjab Pension Funds'
    ],
    'Alfalah Asset Management Limited': [
        'Alfalah Asset Allocation Fund',
        'Alfalah Cash Fund',
        'Alfalah Consumer Index ETF',
        'Alfalah Financial Sector Funds',
        'Alfalah Financial Value Funds',
        'Alfalah GHP Alpha Fund',
        'Alfalah GHP Cash Fund',
        'Alfalah GHP Dedicated Equity Fund',
        'Alfalah GHP Income Fund',
        'Alfalah GHP Income Multiplier Fund',
        'Alfalah GHP Islamic Funds',
        'Alfalah GHP Money Market Fund',
        'Alfalah GHP Pension Fund',
        'Alfalah GHP Prosperity Planning Fund',
        'Alfalah GHP Sovereign Fund',
        'Alfalah GHP Stock Fund',
        'Alfalah Government Securities Funds',
        'Alfalah Income & Growth Fund',
        'Alfalah Islamic Money Market Fund',
        'Alfalah Islamic Rozana Amdani Fund',
        'Alfalah Islamic Sovereign Fund',
        'Alfalah Islamic Stable Return Fund',
        'Alfalah Pension Fund',
        'Alfalah Savings Growth Fund',
        'Alfalah Special Savings Fund',
        'Alfalah Stable Return Fund',
        'Alfalah Strategic Allocation Fund',
        'Alfalah Stock Fund'
    ],
    'Atlas Asset Management Limited': [
        'Atlas Income Fund',
        'Atlas Islamic Cash Fund',
        'Atlas Islamic Dedicated Stock Fund',
        'Atlas Islamic Fund of Funds',
        'Atlas Islamic Income Fund',
        'Atlas Islamic Money Market Fund',
        'Atlas Islamic Stock Fund',
        'Atlas Liquid Fund',
        'Atlas Money Market Fund',
        'Atlas Pension Fund',
        'Atlas Pension Islamic Fund',
        'Atlas Sovereign Fund',
        'Atlas Stock Market Fund',
        'Atlas Punjab Pension Funds'
    ],
    'AWT Investments Limited': [
        'AWT Financial Sector Income Fund',
        'AWT Income Fund',
        'AWT Islamic Asset Allocation Fund',
        'AWT Islamic Income Fund',
        'AWT Islamic Money Market Fund',
        'AWT Islamic Pension Fund',
        'AWT Islamic Stock Fund'
    ],
    'Faysal Asset Management Limited': [
        'Faysal Halal Amdani Funds',
        'Faysal Islamic Asset Allocation Funds',
        'Faysal Islamic Cash Fund',
        'Faysal Islamic Dedicated Equity Fund',
        'Faysal Islamic Financial Growth Funds',
        'Faysal Islamic Financial Planning Fund',
        'Faysal Islamic Mustakil Munafa Fund',
        'Faysal Islamic Pension Fund',
        'Faysal Islamic Savings Growth Fund',
        'Faysal Islamic Sovereign Fund',
        'Faysal Islamic Stock Funds',
        'Faysal Khushal Mustaqbil Fund'
    ],
    'First Capital Investments Limited': [
        'First Capital Mutual Fund'
    ],
    'HBL Asset Management Limited': [
        'HBL Cash Fund',
        'HBL Energy Fund',
        'HBL Equity Fund',
        'HBL Financial Sector Income Funds',
        'HBL Government Securities Fund',
        'HBL Growth Funds',
        'HBL Income Fund',
        'HBL Investment Funds',
        'HBL Islamic Asset Allocation Fund',
        'HBL Islamic Equity Fund',
        'HBL Islamic Fixed Term Funds',
        'HBL Islamic Income Fund',
        'HBL Islamic Money Market Fund',
        'HBL Islamic Pension Fund',
        'HBL Islamic Stock Fund',
        'HBL Mehfooz Munafa Funds',
        'HBL Money Market Fund',
        'HBL Multi Asset Fund',
        'HBL Pension Fund',
        'HBL Stock Fund',
        'HBL Total Treasury ETF'
    ],
    'JS Investments Limited': [
        'JS Cash Fund',
        'JS Fixed Term Munafa Funds',
        'JS Fund of Funds',
        'JS Government Securities Fund',
        'JS Growth Fund',
        'JS Income Fund',
        'JS Islamic Fund',
        'JS Islamic Income Fund',
        'JS Islamic Money Market Fund',
        'JS Islamic Pension Savings Fund',
        'JS Islamic Sarmaya Mehfooz Fund',
        'JS Large Cap Fund',
        'JS Microfinance Sector Fund',
        'JS Momentum Factor ETF',
        'JS Money Market Fund',
        'JS Pension Savings Fund'
    ],
    'Lakson Investments Limited': [
        'Lakson Asset Allocation Developed Markets Fund',
        'Lakson Equity Fund',
        'Lakson Income Fund',
        'Lakson Islamic Money Market Fund',
        'Lakson Islamic Tactical Fund',
        'Lakson Money Market Fund',
        'Lakson Tactical Fund'
    ],
    'Lucky Investments Limited': [
        'Lucky Islamic Cash Fund',
        'Lucky Islamic Energy Fund',
        'Lucky Islamic Fixed Term Funds',
        'Lucky Islamic Income Fund',
        'Lucky Islamic Money Market Fund',
        'Lucky Islamic Pension Fund',
        'Lucky Islamic Stock Fund',
        'Lucky Islamic Punjab Pension Fund'
    ],
    'Mahaana Wealth Limited': [
        'Mahaana IGI Islamic Retirement Fund',
        'Mahaana Islamic Cash Fund',
        'Mahaana Islamic Index ETF'
    ],
    'MCB Investment Management Limited': [
        'MCB Cash Management Optimizer',
        'MCB DCF Fixed Return Fund',
        'MCB DCF Income Fund',
        'MCB Government Securities Plan',
        'MCB Investment Savings Plan',
        'MCB Pakistan Asset Allocation Fund',
        'MCB Pakistan Fixed Return Plans',
        'MCB Pakistan Opportunity Fund',
        'MCB Pakistan Sovereign Fund',
        'MCB Pakistan Stock Market Fund',
        'MCB Pension Funds',
        'Alhamra Cash Management Optimizer',
        'Alhamra Daily Dividend Fund',
        'Alhamra Government Securities Plan I',
        'Alhamra Islamic Asset Allocation Fund',
        'Alhamra Islamic Income Fund',
        'Alhamra Islamic Money Market Fund',
        'Alhamra Islamic Pension Fund',
        'Alhamra Islamic Punjab Pension Fund',
        'Alhamra Islamic Stock Fund',
        'Alhamra Opportunity Fund (Dividend Strategy Plan)',
        'Alhamra Smart Portfolio',
        'Alhamra Wada Fund (Alhamra Wada Plan XVI)'
    ],
    'National Investment Trust Limited (NIT)': [
        'National Investment Unit Trust',
        'NIT Asset Allocation Fund',
        'NIT Government Bond Fund',
        'NIT Income Fund',
        'NIT Islamic Equity Fund',
        'NIT Islamic Income Fund',
        'NIT Islamic Money Market Fund',
        'NIT Islamic Pension Fund',
        'NIT Money Market Fund',
        'NIT Pakistan Gateway ETF',
        'NIT Pension Fund',
        'NIT Social Impact Fund'
    ],
    'NBP Fund Management Limited': [
        'NBP Balanced Fund',
        'NBP Cash Plans',
        'NBP Financial Sector Funds',
        'NBP Fixed Term Munafa Plans',
        'NBP Government Securities Funds',
        'NBP Income Funds',
        'NBP Islamic Funds',
        'NBP Mahana Amdani Fund',
        'NBP Money Market Fund',
        'NBP Pension Funds',
        'NBP Stock Fund'
    ],
    'Pak Oman Asset Management Company Limited': [
        'Pak Oman Advantage Asset Allocation Fund',
        'Pak Oman Advantage Islamic Income Fund',
        'Pak Oman Daily Dividend Fund',
        'Pak Oman Income Fund',
        'Pak Oman Islamic Asset Allocation Fund',
        'Pak Oman Micro Finance Fund'
    ],
    'Pak-Qatar Asset Management Company Limited': [
        'Pak Qatar Asan Munafa Plan',
        'Pak Qatar Asset Allocation Plans',
        'Pak Qatar Cash Plan',
        'Pak Qatar Daily Dividend Plan',
        'Pak Qatar Income Plan',
        'Pak Qatar Islamic Pension Fund',
        'Pak Qatar Islamic Stock Fund',
        'Pak Qatar Khalis Bachat Plan',
        'Pak Qatar Monthly Income Plan'
    ],
    'UBL Fund Managers Limited': [
        'UBL Asset Allocation Fund',
        'UBL Cash Fund',
        'UBL Financial Sector Fund',
        'UBL Fixed Return Plans',
        'UBL Government Securities Fund',
        'UBL Growth & Income Fund',
        'UBL Income Opportunity Fund',
        'UBL Liquidity Funds',
        'UBL Money Market Fund',
        'UBL Pakistan Enterprise ETF',
        'UBL Pension Funds',
        'UBL Retirement Saving Fund',
        'UBL Special Savings Plans',
        'UBL Stock Advantage Fund',
        'Al Ameen Islamic Aggressive Income Fund',
        'Al Ameen Islamic Aggressive Income Plan I',
        'Al Ameen Islamic Asset Allocation Fund',
        'Al Ameen Islamic Cash Fund',
        'Al Ameen Islamic Cash Plan I',
        'Al Ameen Islamic Energy Fund',
        'Al Ameen Islamic Income Fund',
        'Al Ameen Islamic Punjab Pension Fund',
        'Al Ameen Islamic Retirement Savings Fund',
        'Al Ameen Islamic Sovereign Fund',
        'Al Ameen Shariah Stock Fund',
        'Al Ameen Voluntary Pension Fund KPK'
    ]
};
