export interface FundDetails {
    name: string;
    risk: 'LOW' | 'MEDIUM' | 'HIGH';
    isShariah: boolean;
    category: 'MUTUAL_FUND' | 'VPS' | 'ETF';
    type?: string;
}

export const FUNDS_DATA: Record<string, FundDetails[]> = {
    '786 Investments Limited': [
        { name: "786 Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "786 Smart Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
    ],
    'ABL Asset Management Company Limited': [
        { name: "ABL Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "ABL GOKP Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "ABL GOPB Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "ABL Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "ABL Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "ABL GOKP Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "ABL GOPB Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "ABL Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Financial Sector Fund Plan I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Fixed Rate Plan XIX", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Fixed Rate Plan XXI", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Fixed Rate Plan XXII", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Fixed Rate Plan XXIII", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Fixed Rate Plan XXIV", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Government Securities Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Money Market Plan I", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Sovereign Plan I", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Money Market Plan I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Special Saving Fund (ABL Special Saving Plan I)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Special Saving Fund (ABL Special Saving Plan II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Special Saving Fund (ABL Special Saving Plan III)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Special Saving Fund (ABL Special Saving Plan IV)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Special Saving Fund (ABL Special Saving Plan V)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Special Saving Fund (ABL Special Saving Plan VI)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Financial Planning Fund (Conservative Plan)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Financial Planning Fund (Strategic Allocation Plan)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Financial Planning Fund (Active Allocation Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "CPPI) – ABL Islamic Financial Planning Fund (Capital Preservation Plan I)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Financial Planning Fund (Conservative Allocation Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Optimal Asset Allocation Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Allied Finergy Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "ABL Pension Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "ABL Islamic Dedicated Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "ABL Stock Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'AKD Investment Management Limited': [
        { name: "AKD Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AKD Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AKD Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AKD Aggressive Income Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AKD Index Tracker Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AKD Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AKD Opportunity Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Golden Arrow Stock Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'AL Habib Asset Management Limited': [
        { name: "AL Habib Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "AL Habib GOKP Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "AL Habib Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "AL Habib Pension Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "AL Habib GOKP Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "AL Habib Pension Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "AL Habib Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Fixed Return Fund Plan 19", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Fixed Return Fund Plan 20", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Fixed Return Fund Plan 22", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Fixed Return Fund Plan 23", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Fixed Return Fund Plan 24", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Government Securities Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AL Habib Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AL Habib Islamic Savings Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AL Habib Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Sovereign Income Fund Plan 1", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Sovereign Income Fund Plan 2", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Sovereign Income Fund Plan 3", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Asset Allocation Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "AL Habib Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "AL Habib Pension Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "AL Habib Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AL Habib Stock Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'Al Meezan Investment Management Limited': [
        { name: "Meezan Tahaffuz Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "Meezan GOKP Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Meezan Islamic Government of Punjab Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Meezan Tahaffuz Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Meezan Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Daily Income Fund (MDIP I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Daily Income Fund (Meezan Mahana Munafa Plan)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Daily Income Fund (Meezan Munafa Plan I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Daily Income Fund (Meezan Sehl Account Plan) (MSHP)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Daily Income Fund (Meezan Super Saver Plan) (MSSP)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Islamic Asaan Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Paidaar Munafa Plan 35", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Paidaar Munafa Plan 36", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Paidaar Munafa Plan 37", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Paidaar Munafa Plan XXXI", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Rozana Amdani Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Sovereign Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Balanced Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Dynamic Asset Allocation Fund (Meezan Dividend Yield Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Financial Planning Fund of Funds (Aggressive)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Financial Planning Fund of Funds (Conservative)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Financial Planning Fund of Funds (MAAP I)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Financial Planning Fund of Funds (Moderate)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Financial Planning Fund of Funds (Very Conservative Allocation Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Strategic Allocation Fund (MSAP I)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Strategic Allocation Fund (MSAP II)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Strategic Allocation Fund (MSAP III)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Strategic Allocation Fund (MSAP IV)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Strategic Allocation Fund (MSAP V)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Tahaffuz Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "Meezan Tahaffuz Pension Fund (Commodities)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Commodit' },
        { name: "Al Meezan Mutual Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "KSE Meezan Index Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Dedicated Equity Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Energy Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Gold Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Islamic Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Meezan Pakistan ETF", risk: 'HIGH', isShariah: true, category: 'ETF' },
    ],
    'Alfalah Asset Management Limited': [
        { name: "Alfalah GHP Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Alfalah GHP Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "Alfalah Islamic KPK Employee Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Alfalah GHP Pension Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "Alfalah GHP Pension Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "Alfalah Pension Fund - II (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "Alfalah KPK Employee Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "Alfalah Cash Fund - II", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Financial Sector Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Financial Sector Opportunity Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Sovereign Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Government Securities Fund - II", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Government Securities Fund Plan I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Government Securities Fund Plan II", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Rozana Amdani Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Sovereign Fund (Alfalah Islamic Sovereign Plan I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Sovereign Fund (Alfalah Islamic Sovereign Plan II)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Sovereign Fund (Alfalah Islamic Sovereign Plan III)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Stable Return Fund Plan  X", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Stable Return Fund Plan XI", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Islamic Stable Return Fund Plan XII", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Money Market Fund - II", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah MTS Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Savings Growth Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Special Savings Fund - I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Special Savings Fund - II", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Stable Return Fund Plan XX", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Stable Return Fund Plan XXI", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Stable Return Fund Plan XXII", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Stable Return Fund Plan XXIII", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Stable Return Fund Plan XXIV", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Stable Return Fund Plan XXVI", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Asset Allocation Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Financial Value Fund (Alfalah Financial Value Plan I)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Financial Value Fund - II", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Income Multiplier Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Prosperity Planning Fund (Alfalah GHP Islamic Active Allocation Plan II)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Prosperity Planning Fund (Alfalah GHP Islamic Balance Allocation Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Prosperity Planning Fund (Alfalah GHP Islamic Moderate Allocation Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Value Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Prosperity Planning Fund (Alfalah GHP Active Allocation Plan)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Prosperity Planning Fund (Alfalah GHP Conservative Allocation Plan)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Prosperity Planning Fund (Alfalah GHP Moderate Allocation Plan)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Prosperity Planning Fund (Capital Preservation Plan IV)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Value Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Income & Growth Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah KTrade Islamic Plan VII", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah Strategic Allocation Fund Plan - I", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "Alfalah GHP Pension Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "Alfalah Pension Fund - II (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "Alfalah Consumer Index Exchange Traded Fund", risk: 'HIGH', isShariah: false, category: 'ETF' },
        { name: "Alfalah GHP Alpha Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Dedicated Equity Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Dedicated Equity Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alfalah GHP Stock Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alfalah Stock Fund - II", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'Atlas Asset Management Limited': [
        { name: "Atlas Pension Islamic Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Atlas Pension Islamic Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "Atlas KPK Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Atlas Punjab Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Atlas Pension Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "Atlas Pension Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "Atlas Punjab Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "Atlas Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Liquid Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Atlas Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Atlas Sovereign Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Fund of Funds (Atlas Aggressive Allocation Islamic Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Fund of Funds (Atlas Conservative Allocation Islamic Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Fund of Funds (Atlas Moderate Allocation Islamic Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Pension Islamic Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "Atlas Pension Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "Atlas Dividend Yield Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Atlas Financial Sector Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Dedicated Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Atlas Stock Market Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'AWT Investments Limited': [
        { name: "AWT Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "AWT Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "AWT Islamic Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "AWT Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "AWT Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
    ],
    'EFU Life Assurance Ltd': [
        { name: "EFU Hemayah Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "EFU Hemayah Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "EFU Hemayah Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
    ],
    'Faysal Asset Management Limited': [
        { name: "Faysal Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "Faysal Islamic KPK Government Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Faysal Islamic Punjab Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Faysal Halal Amdani Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Halal Amdani Fund II", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Halal Amdani Fund III", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Mustakil Munafa Fund (Faysal Islamic Mehdood Muddat Plan I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Mustakil Munafa Fund (Faysal Islamic Mehdood Muddat Plan VI)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Mustakil Munafa Fund (Faysal Islamic Mehdood Muddat Plan XIII)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Mustakil Munafa Fund (Faysal Islamic Mehdood Muddat Plan XIV)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Mustakil Munafa Fund (Faysal Islamic Mehdood Muddat Plan XV)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Savings Growth Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Sovereign Fund (Faysal Islamic Sovereign Plan I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Sovereign Fund (Faysal Islamic Sovereign Plan II)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Special Income Plan I", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Asset Allocation Fund II", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Asset Allocation Fund III (Faysal Shariah Flex Plan I)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Asset Allocation Fund III (Faysal Shariah Flex Plan II)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Asset Allocation Fund III (Faysal Shariah Flex Plan III)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Financial Growth Fund (Faysal Islamic Financial Growth Plan I)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Financial Growth Fund (Faysal Islamic Financial Growth Plan II)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Financial Growth Fund II", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Financial Planning Fund II (Faysal Priority Ascend Plan I)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Financial Planning Fund II (Faysal Priority Ascend Plan II)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Financial Planning Fund II (Faysal Priority Ascend Plan III)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Khushal Mustaqbil Fund (Faysal Barak’ah Women Savers Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Khushal Mustaqbil Fund (Faysal Nu’umah Women Savers Plan)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Faysal Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "Faysal Islamic Dedicated Equity Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Faysal Islamic Stock Fund II", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
    ],
    'HBL Asset Management Limited': [
        { name: "HBL Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "HBL KPK Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "HBL Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "HBL KPK Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "HBL Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Financial Sector Income Fund Plan I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Financial Sector Income Fund Plan II", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Government Securities Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Fixed Term Fund Plan II", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Savings Plan I", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "HBL Mehfooz Munafa Fund Plan IV", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Mehfooz Munafa Fund Plan X", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Mehfooz Munafa Fund Plan XI", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Mehfooz Munafa Fund Plan XII", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Mehfooz Munafa Fund Plan XIII", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "HBL Multi Asset Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Pension Fund", risk: 'HIGH', isShariah: true, category: 'VPS' },
        { name: "HBL Pension Fund", risk: 'HIGH', isShariah: false, category: 'VPS' },
        { name: "HBL Energy Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Equity Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Growth Fund-Class A", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Growth Fund-Class B", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Investment Fund-Class A", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Investment Fund-Class B", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Equity Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "HBL Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "HBL Stock Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "HBL Total Treasury Exchange Traded Fund", risk: 'HIGH', isShariah: false, category: 'ETF' },
    ],
    'Mahaana Wealth Limited': [
        { name: "Mahaana IGI Islamic Retirement Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Mahaana Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Mahaana IGI Islamic Retirement Fund", risk: 'HIGH', isShariah: true, category: 'VPS' },
        { name: "Mahaana Islamic Index Exchange Traded Fund", risk: 'HIGH', isShariah: true, category: 'ETF' },
    ],
    'JS Investments Limited': [
        { name: "JS Islamic Pension Savings Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "JS Islamic Pension Savings Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "JS KPK Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "JS Punjab Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "JS Pension Savings Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "JS Pension Savings Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "JS KPK Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "JS Punjab Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "JS Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund (JS Fixed Term Munafa Plan I)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund (JS Fixed Term Munafa Plan XIV)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund (JS Fixed Term Munafa Plan XIX)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund (JS Fixed Term Munafa Plan XV)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund (JS Fixed Term Munafa Plan XVI)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund (JS Fixed Term Munafa Plan XX)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund (JS Fixed Term Munafa Plan XXI)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund II (JS Fixed Term Munafa Plan I)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund II (JS Fixed Term Munafa Plan IV)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund II (JS Fixed Term Munafa Plan V)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fixed Term Munafa Fund II (JS Fixed Term Munafa Plan VI)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Government Securities Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "JS Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "JS Islamic Sarmaya Mehfooz Fund (JS Islamic Sarmaya Mehfooz Plan 1)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "JS Islamic Sarmaya Mehfooz Fund Plan 2 2020", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "JS Microfinance Sector Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Fund of Funds", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Unit Trust of Pakistan", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Islamic Pension Savings Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "JS Pension Savings Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "JS Growth Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Islamic Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "JS Large Cap Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "JS Momentum Factor Exchange Traded Fund", risk: 'HIGH', isShariah: false, category: 'ETF' },
    ],
    'Lakson Investments Limited': [
        { name: "Lakson Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Lakson Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lakson Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Lakson Asset Allocation Developed Markets Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Lakson Islamic Tactical Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lakson Tactical Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Lakson Equity Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'Lucky Investments Limited': [
        { name: "Lucky Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Lucky Islamic Punjab Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Lucky Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Fixed Term Fund Plan IX", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Fixed Term Fund Plan V", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Fixed Term Fund Plan VII", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Fixed Term Fund Plan XII", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Pension Fund", risk: 'HIGH', isShariah: true, category: 'VPS' },
        { name: "Lucky Islamic Energy Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Lucky Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
    ],
    'MCB Investment Management Limited': [
        { name: "Alhamra Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Alhamra Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "Alhamra Islamic Punjab Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "MCB Alhamra KPK Govt Employees Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Pakistan Pension Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "Pakistan Pension Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "MCB KPK Govt Employees Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "MCB Punjab Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "Alhamra Cash Management Optimizer", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alhamra Daily Dividend Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alhamra Government Securities Plan I", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alhamra Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alhamra Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alhamra Wada Fund (Alhamra Wada Plan XVI)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "MCB Cash Management Optimizer", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "MCB DCF Fixed Return III (Plan IV)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "MCB DCF Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "MCB Government Securities Plan I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "MCB Pakistan Fixed Return Plan 25", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "MCB Pakistan Sovereign Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pakistan Cash Management Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pakistan Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alhamra Islamic Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alhamra Smart Portfolio", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "MCB Investment Savings Plan I", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "MCB Pakistan Asset Allocation Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "MCB Pakistan Opportunity Fund (MCB Pakistan  Dividend Yield Plan)", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pakistan Capital Market Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pakistan Income Enhancement Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Alhamra Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "Pakistan Pension Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "Alhamra Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Alhamra Opportunity Fund (Dividend Strategy Plan)", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "MCB Pakistan Stock Market Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'National Investment Trust Limited (NIT)': [
        { name: "NIT Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "NIT Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "NIT KP Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "NIT Pension Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "NIT Pension Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "NIT KP Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "NIT - Government Bond Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NIT - Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NIT Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NIT Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NIT Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NIT Social Impact Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NIT Asset Allocation Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NIT Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "NIT Pension Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "NIT Pension Fund (Commodities)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Commodit' },
        { name: "National Investment Unit Trust", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NIT Islamic Equity Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NIT Pakistan Gateway Exchange Traded Fund", risk: 'HIGH', isShariah: false, category: 'ETF' },
    ],
    'NBP Fund Management Limited': [
        { name: "NAFA Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "NAFA Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "NBP GoKP Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "NBP Islamic Punjab Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "NAFA Pension Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "NAFA Pension Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "NBP GoKP Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "NBP Punjab Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "NBP Cash Plan I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Cash Plan II", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Financial Sector Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XIIA (NBP Mustahkam Fund II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XIII (NBP Mustahkam Fund II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XIVA (NBP Mustahkam Fund II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XIX", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XIXA (NBP Mustahkam Fund II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XVIA (NBP Mustahkam Fund II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XVIIA (NBP Mustahkam Fund II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Fixed Term Munafa Plan XVIIIA (NBP Mustahkam Fund II)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Government Securities Liquid Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Government Securities Plan IV", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Government Securities Plan VIII", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Government Securities Savings Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Income Opportunity Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Income Plan I", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Daily Dividend Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Fixed Term Munafa Plan IIA (NBP Islamic Mustahkam Fund)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Fixed Term Munafa Plan IIIA (NBP Islamic Mustahkam Fund)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Fixed Term Munafa Plan IVA (NBP Islamic Mustahkam Fund)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Fixed Term Munafa Plan VIII (NBP Islamic Mustahkam Fund)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Government Securities Plan III", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Mahana Amdani Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Money Market Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Principal Protection Fund I (NBP Islamic Principal Protection Plan I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Principal Protection Fund II (NBP Islamic Principal Protection Fund I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Principal Protection Fund III (NBP Islamic Principal Protection Plan I)", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Savings Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Mahana Amdani Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Riba Free Savings Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Savings Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Balanced Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Sarmaya Izafa Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Sarmaya Izafa Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NAFA Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "NAFA Pension Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "NBP Financial Sector Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Energy Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "NBP Pakistan Growth Exchange Traded Fund", risk: 'HIGH', isShariah: false, category: 'ETF' },
        { name: "NBP Stock Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'Pak Oman Asset Management Company Limited': [
        { name: "Askari Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Askari Sovereign Yield Enhancer", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pak Oman Advantage Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Oman Daily Dividend Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Oman Income Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pak Oman Micro Finance Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Askari High Yield Scheme", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pak Oman Advantage Asset Allocation Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Pak Oman Islamic Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
    ],
    'Pak-Qatar Asset Management Company Limited': [
        { name: "Pak Qatar Asan Munafa Plan", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Cash Plan", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Daily Dividend Plan", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Income Plan", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Khalis Bachat Plan", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Monthly Income Plan", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Islamic Pension Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Pak Qatar Islamic Pension Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "Pak Qatar GoKP Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Pak Qatar GoPB Islamic Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Pak Qatar Asset Allocation Plan I (PQAAP  IA)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Asset Allocation Plan II (PQAAP  IIA)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak-Qatar Asset Allocation Plan III (PQAAP  IIIA)", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Islamic Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Pak Qatar Islamic Pension Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
    ],
    'UBL Fund Managers Limited': [
        { name: "Al Ameen Islamic Retirement Savings Fund (Money Market)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Money Market' },
        { name: "Al Ameen Islamic Punjab Pension Fund", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "Al Ameen Islamic Retirement Savings Fund (Debt)", risk: 'LOW', isShariah: true, category: 'VPS', type: 'Debt' },
        { name: "Al Ameen Voluntary Pension Fund KPK", risk: 'LOW', isShariah: true, category: 'VPS' },
        { name: "UBL Retirement Saving Fund (Money Market)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Money Market' },
        { name: "UBL Punjab Pension Fund", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "UBL Retirement Saving Fund (Debt)", risk: 'LOW', isShariah: false, category: 'VPS', type: 'Debt' },
        { name: "UBL Voluntary Pension Fund KPK", risk: 'LOW', isShariah: false, category: 'VPS' },
        { name: "Al Ameen Islamic Cash Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Islamic Cash Plan I", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Islamic Income Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Islamic Sovereign Fund", risk: 'LOW', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "UBL Cash Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan II (AB)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan II (M)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan III (X)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan III (Y)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan III (Z)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan IV (G)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan IV (M)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Fixed Return Plan IV (O)", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Government Securities Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Income Opportunity Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Liquidity Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Liquidity Plus Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Money Market Fund", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Income) – UBL Special Savings Plan V", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Income) – UBL Special Savings Plan X", risk: 'LOW', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Islamic Aggressive Income Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Islamic Aggressive Income Plan I", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Islamic Asset Allocation Fund", risk: 'MEDIUM', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "UBL Asset Allocation Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Growth & Income Fund", risk: 'MEDIUM', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Islamic Retirement Savings Fund (Equity)", risk: 'HIGH', isShariah: true, category: 'VPS', type: 'Equity' },
        { name: "UBL Retirement Saving Fund (Equity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Equity' },
        { name: "Al Ameen Islamic Energy Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "Al Ameen Shariah Stock Fund", risk: 'HIGH', isShariah: true, category: 'MUTUAL_FUND' },
        { name: "UBL Financial Sector Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
        { name: "UBL Pakistan Enterprise Exchange Traded Fund", risk: 'HIGH', isShariah: false, category: 'ETF' },
        { name: "UBL Retirement Saving Fund (Commodity)", risk: 'HIGH', isShariah: false, category: 'VPS', type: 'Commodit' },
        { name: "UBL Stock Advantage Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
    'First Capital Investments Limited': [
        { name: "First Capital Mutual Fund", risk: 'HIGH', isShariah: false, category: 'MUTUAL_FUND' },
    ],
};
